version: '3'
services:
  php:
    image: php:8.2-fpm
    ports:
      - "9000:9000"
    volumes:
      - ${DATABASE_DIR}:/app/database:rw
      - ${APP_DIR}:/var/www/html
      - ${PLEX_DIR}:/usr/lib/plexmediaserver
    command: sh -c "chown -R www-data:www-data /var/www
      && chown -R www-data:www-data /app/database               
      && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && composer install --no-dev
      && php-fpm -F"

  nginx:
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_DIR}:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    command: nginx -g "daemon off;"

volumes:
  database:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${PWD}/database"

